### PR TITLE
General Fixes for Newest Posts

### PR DESCRIPTION
**Pull request by TJScalzo**
Just as the title of the issue says, this is a pull request with fixes for all of the newest posts. Almost all of the changes were very minor. The only two major problems I noticed were the creator of [Unicalendar](https://inspiring.online/this-emoji-calendar-will-brighten-your-day-every-day./) is named Josh Williams, not John Williams; and MrGumix's [gameplay demo](https://inspiring.online/real-time-ascii-rendering-in-a-gameplay-demo-yes-please./) is called Asciicker, not AsciiKicker.

@tholman, please let me know if you'd like me to submit these fixes as separate pull requests for each post or if there are any changes you're unhappy with.

### CODE REVIEW

**Comment by tholman** [comment]
Omg I’m the worst, haha, huge mistakes -_-. Perhaps I gotta rethink my “fast Siri ting” agenda. Thank youuuu, these are so good.

**Comment by TJScalzo** [comment]
> Perhaps I gotta rethink my “fast Siri ting” agenda.

I think that method works really well for getting ideas out of your head and into the computer. Then you have to take some time to go through it and see whether it will make sense to someone else.

**Comment by tholman** [comment]
Lol that was a big ole typo on “fast composing” ironically.

**Comment by TJScalzo** [comment]
I'll be honest, I thought it was slang for using Siri or something.

**Pull request merged**
