### PR TITLE
Add Animated book covers(fixes #15)

### LINKED ISSUE #15: [proposal] - Animated book covers
https://vimeo.com/141891887

... will need to add support for vimeo embeds too.

### PR DESCRIPTION
**Pull request by vaidaslamanauskas**

### CODE REVIEW

**Comment by vaidaslamanauskas** [comment]
Date slightly in front due to #30 
Or is it not necessary?

**Comment by tholman** [comment]
Its a good question actually. If two dates are the same, how does jekyll handle it? ... or would we have to add in like "weight: 1" and "weight: 2" to the two posts on the one day, to order them.

**Comment by tholman** [comment]
#30 was created, because I wasn't sure (and never tested)... what do people usually do in this situation :/

Ultimately we'd love to have multiple posts in a day.

**Comment by vaidaslamanauskas** [comment]
I am pretty sure we could work it out by specifying hours if theres more than one post in a single day.
YYYY-MM-DD HH:MM:SS

**Comment by vaidaslamanauskas** [comment]
Yeah. It should work. Date set in front matter overrides the one from post title. Hurray!

**Comment by tholman** [comment]
Awesome post :)

**Pull request merged**
