### PR TITLE
Fixed several issues in Pixel post

### PR DESCRIPTION
**Pull request by TJScalzo**
#### Things I fixed/changed:
- authorUrl
- url->link
- pixel->Pixel
- Phrasing

Helps #153

### CODE REVIEW

**Comment by TJScalzo** [comment]
What I mean by url->link is that @Haroenv accidentally made the link to the external site the url that the image and header link to.

**Comment by Haroenv** [comment]
I personally like "palm" better because it's less like the same phrasing a few posts lower

**Comment by tholman** [comment]
I liked palm too :D We should probably be a little more careful editing other peoples text (still fixing typos of course)

My bad for quickly merging!

**Comment by TJScalzo** [comment]
@tholman and @Haroenv, I'm sorry! I noticed that there wasn't a period at the end of the sentence and just got caught up in revising it.

**Pull request merged**
