### PR TITLE
Updated post "Do it!"

### PR DESCRIPTION
**Pull request by JohJakob**
Fixed some typos

### CODE REVIEW

**Comment by JohJakob** [comment]
:P

**Comment by tholman** [comment]
:dancer: 

Ooh, good fixes. Although the top line makes sense as it is (I think?) " If so, the do it chrome extension is for you" rather than "If so, then do it chrome extension is for you"

**Comment by JohJakob** [comment]
Oh, yeah. You're right!

**Comment by JohJakob** [comment]
Now it should be correct.

**Comment by tholman** [comment]
Awesome!

**Comment by JohJakob** [comment]
That makes quite fun!

**Comment by tholman** [comment]
The real miracle is how I've survived this far in life, with my spelling skills!

**Comment by JohJakob** [comment]
:D

**Pull request merged**
