### PR TITLE
Brick Block 

### PR DESCRIPTION
**Pull request by nitinthewiz**
Hey,

My proposal was accepted. I followed the wiki as well as I understood. First time posting, so I hope I got everything right.

Maybe the image size is too big?

Cheers!

### CODE REVIEW

**Comment by Haroenv** [comment]
If the image seems big, you can try running it through imageOptim

**Comment by Haroenv** [comment]
Thanks for your contribution!

**Comment by TJScalzo** [comment]
@nitinthewiz If imageOptim doesn't remove very much from the image's size, you could also scale it down a little bit. The image will never be displayed at a size larger than 214 pixels so it can be scaled to any size above that.

**Comment by nitinthewiz** [comment]
I've updated the files, but I'm still looking into how to update this commit... 😜

**Comment by nitinthewiz** [comment]
Ok, apparently I don't need to do anything. I removed the big image and replaced it with a scaled down file. I also updated the text file to change the date. 😊

**Comment by tholman** [comment]
👍

**Pull request merged**
