### PR TITLE
Use correct contributing address

### PR DESCRIPTION
**Pull request by krikmo**

### CODE REVIEW

**Comment by tholman** [comment]
:pray:

**Comment by krikmo** [comment]
:smile:

**Comment by krikmo** [comment]
There's the same problem with the "Join in?" link, should all pages be changed or just the menu.html file?

**Comment by tholman** [comment]
Ahh, changing it in
https://github.com/tholman/inspiring-online/blob/gh-pages/_includes/menu.html
should do the trick for the other pages.

On Fri, Feb 12, 2016 at 10:21 AM, Krik Mohammed <notifications@github.com>
wrote:

> There's the same problem with the "Join in?" link, should all pages be
> changed or just the menu.html file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/inspiring-online/pull/97#issuecomment-183371338>
> .
>



-- 
Tim Holman
tholman.com

**Comment by krikmo** [comment]
Boom, [done](https://github.com/tholman/inspiring-online/pull/98).

**Pull request merged**
