### PR TITLE
Added post about paper letter typography

### LINKED ISSUE #145: [proposal] - Paper letter typography
Thought these were neat: http://jxnblk.com/papercraft/

### PR DESCRIPTION
**Pull request by 2016rshah**
Fixes #145

### CODE REVIEW

**Comment by tholman** [comment]
:pray:

**Comment by tholman** [comment]
Weird that it popped up as the second post, not the first :/

**Comment by TJScalzo** [comment]
@tholman, it _is_ the second post today. But yeah, alphabetically, it should be first. Odd...

**Comment by tholman** [comment]
Ahh, I'm in a different timezone so felt like different days from here.... makes sense -_-

No biggie.

**Comment by tholman** [comment]
Also, two in one day, awesome!

**Pull request merged**
