### PR TITLE
Improved responsiveness of menu

### PR DESCRIPTION
**Pull request by syntiux**
I added media queries to make the menu visible on smaller viewports. #13

### CODE REVIEW

**Comment by tholman** [comment]
Amazing! Will check this out tonight! :dancer:

**Comment by syntiux** [comment]
I added a very simple author attribution to the list of all posts, It's now in the same pull request. Maybe you could review it as well :) It's a start on #12.

**Comment by tholman** [comment]
Will do!

**Comment by syntiux** [comment]
Somehow the favicon commit ended up here as well. I read about how pull requests work and my next contributions will be in topic-specific pull requests. :)

**Comment by tholman** [comment]
Sweet!

I still haven't checked it out yet, but tonight will be the night!

On Mon, Oct 26, 2015 at 7:40 PM, Daniel Federschmidt <
notifications@github.com> wrote:

> Somehow the favicon commit ended up here as well. I read about how pull
> requests work and my next contributions will be in topic-specific pull
> requests. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/inspiring-online/pull/21#issuecomment-151315123>
> .
>



-- 
Tim Holman
tholman.com

**Comment by HipsterBrown** [comment]
@syntiux Could you add some screenshots, a gif, or short screencast of your changes/additions? It would be really helpful for quick, visual reviews.

**Comment by tholman** [comment]
Ok, just checked this out. We should **definitely** split this up into a few pulls. So we can talk about individual parts. The favicon is awesome, I'd merge that now, if I could (but its tied into the other things)

How do you feel about cherry picking the individual parts out? and we can get your awesome stuff in!

**Comment by syntiux** [comment]
Sure, totally agree. I will close this pull request then and create individual ones with the specific changes in them later today. Thanks for your help! It's my first time contributing using pull requests ;).

**Pull request closed without merging**
