### PR TITLE
New types applied to posts

### PR DESCRIPTION
**Pull request by TJScalzo**
I tried to change them to a type that better matches what they're about. I added these types:
- Talk
- Resource
- Coding
- CodePen
- Typography
- CSS Madness
- Beautiful

(Helps with #133)

### CODE REVIEW

**Comment by TJScalzo** [comment]
Oh, I didn't realize that commit would get added to this pull request. I'll try to undo it.

**Comment by TJScalzo** [comment]
Well, it sort of relates to what I'm doing if I change the pull request's title. Is it okay if I do things this way or should I split them up into separate pull-requests?

**Comment by TJScalzo** [comment]
So... I don't know how to split them up into different pull-requests. If it's necessary that these commits be split up can someone point me in the right direction?

**Comment by JohJakob** [comment]
@TJScalzo No, it's not necessary.

**Pull request merged**
