### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by JohJakob**
Updated posts "Neven Mrgan on Why Skeuomorphism Is Like a Classic Car",
"CSSgram", "Trump Gasm", "FrankenSim", "Matt Deslauriers JavaScript
Sketches" and "TypeSource"

### CODE REVIEW

**Comment by tholman** [comment]
:pray:

**Comment by vaidaslamanauskas** [comment]
:pray: Not sure about 'delightful' fix though. I think it changes the meaning?

**Comment by JohJakob** [comment]
I don't think so. "delightfully" is an adverb, "delightful" is an adjective, but both mean the same. "delightful" just sounded better in my ears.

**Comment by tholman** [comment]
You're both better at english than me... Johannes has been doing a great job, but Vaidas, its your post. I can change it back if you'd prefer?

**Comment by vaidaslamanauskas** [comment]
From my understanding, 'delightful grotesque' leaves 'grotesque' alone as is. 'Delightfully grotesque' works like improvement for grotesque. Anyway, leave it as is Tim :)

**Comment by JohJakob** [comment]
Ah, now I understand your meaning 😄 . You're totally right. I'll change it tomorrow (it's 10.20 pm here).

**Comment by tholman** [comment]
Appreciate it bigtime! Haha, the whole site would be a total mess without the both of you :)

**Comment by vaidaslamanauskas** [comment]
Nah, it wouldn't :heart:

**Pull request merged**
