### PR TITLE
adds jetlag.photo

### LINKED ISSUE #127: [proposal] - Jetlag
http://jetlag.photos/

...

I gotta stop being lazy and stop proposing, and start adding some of these!

### PR DESCRIPTION
**Pull request by Haroenv**
Fixes #127

### CODE REVIEW

**Comment by JohJakob** [comment]
@Haroenv :pray:

**Comment by Haroenv** [comment]
Sure the frontmatter is correct?

**Comment by TJScalzo** [comment]
The date in the name of the file isformatted incorrectly.

**Comment by TJScalzo** [comment]
2016-3-3 should be 2016-03-03

**Comment by TJScalzo** [comment]
Also, the italics were never closed, that might cause problems.

**Comment by TJScalzo** [comment]
Lastly, I feel like a little bit more should be written about this than just a summary that can be found on the website.

**Comment by JohJakob** [comment]
@Haroenv @TJScalzo I didn't notice the open italics. You better learn some Markdown ;)

**Comment by TJScalzo** [comment]
Things to change:
- Name of file
- Close the italics
- Perhaps add more content; it seems a little sparse. Take a look at other posts for ideas on what to write.

**Comment by Haroenv** [comment]
Yep, didn't realise what the underscore was for and didn't notice it was closed on other posts. 

The title doesn't technically matter, since other posts have omitted the leading 0 as well

I'll write some more then

**Comment by JohJakob** [comment]
@Haroenv :+1:

**Comment by TJScalzo** [comment]
Might you also add an image? I'm not sure what it should be of seeing as the entire website is about images. But a picture of the interesting transition that is used could work.

**Comment by TJScalzo** [comment]
>The title doesn't technically matter, since other posts have omitted the leading 0 as well
The post didn't show up when I opened the site so I thought that might have been the problem, my bad.

**Comment by JohJakob** [comment]
@TJScalzo It takes some time to apply changes.

**Comment by TJScalzo** [comment]
@JohJakob I realize that now, thank you.

**Pull request merged**
