### PR TITLE
Add jetlag

### PR DESCRIPTION
**Pull request by Haroenv**
This should have no merge conflicts I think

### CODE REVIEW

**Comment by JohJakob** [comment]
@Haroenv Yep, perfect!

**Comment by Haroenv** [comment]
What a ride ;)

**Comment by TJScalzo** [comment]
:smile:

**Comment by tholman** [comment]
Great post, thanks @Haroenv!

**Comment by Haroenv** [comment]
No problem, next time without the issues :smile:

**Pull request merged**
