### PR TITLE
Created visual link to Github

### PR DESCRIPTION
**Pull request by TJScalzo**
I used @tholman's code found [here](http://tholman.com/github-corners/#) to create it. I altered it a little bit, as I mentioned in #31 [here](https://github.com/tholman/inspiring-online/issues/31#issuecomment-189700340), so that the cursor changes in specific ways. 

#### I have no idea how/if this works on mobile
The wifi I'm on right now doesn't allow my phone to connect to my computer's ip address. I'll check it out when I get onto a different network.

### CODE REVIEW

**Comment by tholman** [comment]
Ooh, this is exactly what I had in mind when I made the github corners... just never got around to adding them...

I was thinking though, that I'd like to make them about half as small as they are not, to really be unobtrusive. What'dya think?

**Comment by TJScalzo** [comment]
## Alright, time for some tests.
This is what it looks like now:
screen shot 2016-02-27 at 3 39 42 pm
This is what it looks like half as large:
screen shot 2016-02-27 at 3 40 40 pm
That's very small... This is it at three quarters of the original:
screen shot 2016-02-27 at 3 43 28 pm
Personally, I like it at 80px by 80px but it's up to you, @tholman.

(Also, tiny question: Should I submit the code that I made in the GitHub Corners repository that alters the cursor?)

**Comment by tholman** [comment]
Lets go with half (perhaps we should do top right instead of left, to balance the page a little more.

For the cursor thing... since the whole square technically links to the page, it'd kinda be wrong to not do the cursor being a pointer when its not in the triangle... just for UX's sake.

**Comment by TJScalzo** [comment]
Okay! I'm new to pull requests so would I close this one and then resubmit one with it in the other corner and without the cursor changing?

**Comment by tholman** [comment]
Perfect! (Really appreciate it, too!)

On Sat, Feb 27, 2016 at 3:55 PM, Tim Scalzo <notifications@github.com>
wrote:

> Okay! I'm new to pull requests so would I close this one and then resubmit
> one with it in the other corner and without the cursor changing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/inspiring-online/pull/112#issuecomment-189723809>
> .
>



-- 
Tim Holman
tholman.com

**Comment by TJScalzo** [comment]
Got it. See you soon with a new pull request!

**Pull request closed without merging**
