### PR TITLE
My work - Newsbook

### PR DESCRIPTION
**Pull request by Ananthavijay**
Check it here : https://github.com/Ananthavijay/News-Book

### CODE REVIEW

**Comment by Ananthavijay** [comment]
for my image this is the PR : https://github.com/tholman/inspiring-online/pull/291/commits/0faa0836079cc09920515095d23f2c105cc2aaa9

**Comment by JohJakob** [comment]
Hey @Ananthavijay, Inspiring Online is not a place to post personal work/projects, as you can read [here](https://github.com/tholman/inspiring-online#what-we-dont-like):

> Please don't post your own things. I know self promoting is fun, but it's kind of against the spirit of what we're trying to do.

**Comment by Ananthavijay** [comment]
so will u add it  or not @johjakob

**Comment by JohJakob** [comment]
@Ananthavijay I opened an [issue](https://github.com/tholman/inspiring-online/issues/292) where we can discuss that. I would like to add your post but we have to follow our own rules somehow.

**Comment by Ananthavijay** [comment]
yes thanks

**Pull request closed without merging**
