### PR TITLE
Add Trump Gasm(fixes #4)

### LINKED ISSUE #4: [proposal] - Trump Gasm
http://omg.topherchris.com/TRUMPGASM/

### PR DESCRIPTION
**Pull request by vaidaslamanauskas**
Not sure about the post :)

### CODE REVIEW

**Comment by tholman** [comment]
Haha, I'm 100% sure about this one. This is so so good

**Comment by tholman** [comment]
I'm thinking, perhaps we'll change the type of this one from "inspiration" to "weirdwideworld" or something ;)

**Comment by vaidaslamanauskas** [comment]
I was going to ask about types. Not much to inspire here :)

**Comment by vaidaslamanauskas** [comment]
"weirdwideworld", like it

**Comment by tholman** [comment]
Yeah, its more of a foresight of something we may want to do... not really doing anything it it just yet :)

**Comment by vaidaslamanauskas** [comment]
Dang, it is really good work starter. Will try to "pull request" consistently. Wish more peeps would do it too.

**Comment by tholman** [comment]
:)

Its early, really. The project is set up to grow well though, I think. So many little fun uses, and things like that :)

Sometimes its also an awesome unblocker, to commit something and get your head in the right space for the new day :)

**Comment by vaidaslamanauskas** [comment]
Exactly that :)

**Pull request merged**
