### PR TITLE
Added basic authorship notion to the list of articles as well as to each individual post

### PR DESCRIPTION
**Pull request by syntiux**

### CODE REVIEW

**Comment by tholman** [comment]
Not ignoring this! Just haven't quite got there yet! :)

**Comment by tholman** [comment]
Used some of your suggestions, and ended up putting it in the right bar... of course this makes the responsive nature worse, but thats a problem to overcome in the future.

I wonder if, on the main page, the right bar can sit there, but the content could change in it, as you scroll down. Something for us to think about!

**Comment by tholman** [comment]
Thanks for kicking this off, seriously, super motivating.

**Comment by syntiux** [comment]
Looks great - I really like the idea of having the bar changing as you scroll down the page :+1:

**Pull request merged**
