### PR TITLE
Pixels

### PR DESCRIPTION
**Pull request by Haroenv**
Wait a second to merge, I'm still uploading the gif :1234:

### CODE REVIEW

**Comment by vaidaslamanauskas** [comment]
Don't like the wording "to look at it at as" :)

**Comment by JohJakob** [comment]
@Haroenv You forgot the last line/footer: link - by creator.

**Comment by Haroenv** [comment]
yep @JohJakob done now I think

**Comment by JohJakob** [comment]
@Haroenv I think you have to add "it" after "try to look at".

**Comment by vaidaslamanauskas** [comment]
Do we want gifs?

**Comment by Haroenv** [comment]
I did my best to keep it low in size, it's only 500k

**Comment by vaidaslamanauskas** [comment]
I wouldn't say only :)

**Comment by Haroenv** [comment]
That's small for a gif, and only two other images :smile:

**Comment by JohJakob** [comment]
@vaidaslamanauskas One or two GIFs in a month are OK. Imagine the people browsing 9GAG on their mobile phones every day!

**Comment by Haroenv** [comment]
For a reference, I just checked and the images currently on the front page are each between 300k and 550k, so it isn't even that much of an outlier

**Comment by vaidaslamanauskas** [comment]
@Haroenv image sizes is up for a fix.

**Comment by vaidaslamanauskas** [comment]
It is not a guideline :)

**Comment by tholman** [comment]
Weird, this one didn't appear on the site? :/

**Comment by tholman** [comment]
totally cool with gifs, for the record. Although starting to think we do need to figure out something to do with images, since they're clogging the repo size a bit. I wonder what people do...

**Pull request merged**
