### PR TITLE
Colorful Categories & Generative Pattern

### LINKED ISSUE #318: Background patterns for other categories
Currently `code` has a background pattern of 0 & 1's, that sit within the triangle on the posts. I need to create some more small repetitive tiles for.
- games (space invaders tiled)
- art (perhaps some generative art)
- aesthetic (not sure)
- take my money (dollar signs)
... perhaps a couple of others

### LINKED ISSUE #326: Pattern Stretches Inside Triangle
When the triangle changes size with the window, the pattern also changes size. So although the pattern inside of the triangle will always _load_ at the same size, if the window size changes, the pattern will end up bigger or smaller than when it loaded.

**Example:**
Screen Recording 2020-01-18 at 10 49 37 PM 2
I'm pretty sure this isn't intentional since the pattern size is reset when the page is reloaded at the new window size. 

From what I can tell, this is happening because `vw` is used to define the size of the canvas. Since the pattern is created when the page loads, it's rendered at the original size of the canvas. But when the window is resized the pattern isn't re-rendered and so it just stretches or squishes to fill the triangle as necessary. 

I'm unfamiliar with HTML Canvas, but I'm not sure if there's a way to prevent the pattern from scaling like this without completely changing how the pattern is rendered/created/applied to the canvas.

### LINKED ISSUE #337: Colors for Categories
I played around for a bit and I came up with two main ideas for adding color to categories:
Screen Shot 2020-01-26 at 1 19 04 PMScreen Shot 2020-01-26 at 1 19 18 PM I made these by drawing a colored triangle over the pattern and setting the global blend mode to multiply so the pattern shows through.

Personally, I prefer the gradient since it has some bright, highly saturated color without being overwhelming. However, on mobile it has some problems because the bright part overlaps with the colorful category title which ends up needing an outline to be readable.

Of course, these are just two basic ideas that can be modified or combined if necessary. It's incredible the flexibility you have when using HTML canvas!

If these ideas seem reasonable and/or match the aesthetic of the site, I can clean up my code and push it to a branch for perusing.

### PR DESCRIPTION
**Pull request by TJScalzo**
Fills the triangles on the side of posts with a randomized grid of triangles and applies a themed color based on the post's category. 

(Fixes #337 - Fixes #326 - Fixes #318)

### CODE REVIEW

**Comment by tholman** [comment]
Wow wow wow. I'll get around to looking this code over in the next day or two. V excited about this!

**Comment by TJScalzo** [comment]
I just tested the site on my MacBook's display (I had been using an external display previously), and using `window.devicePixelRatio` doesn't seem to work as intended on Safari or Firefox. Everything is scaled too large. Removing the `dpr` variable from the existing code seems to fix it.

**Comment by tholman** [comment]
Ok, I've had a little play around with this, I'm liking it! 

Some smart stuff in there as well, /w the color picking.

Whatever idea I had in my head seemed a little hard to get out in the moment, but I fixed the dpr stuff here (https://github.com/tholman/inspiring-online/commit/7355c487e21f8fb3afe191a9221e5edb3a209d3d) ... I lightened the canvas a little bit as well (could probably be done by changing the colors to be a little lighter, but this works well)

I think with these changes we're probably good to go. I like this idea of generative flair for the posts, so I could see myself getting a random idea and wanting to mix these up in the future... but that said, you've opened the door to some cool areas to explore.

I'll prob pull out the javascript doing the category styling at some point and move that to css as well. Cleaner that way. But all in all, good stuff! 

Lmk what you think, and I'll merge this in, in the next few days.

**Comment by TJScalzo** [comment]
Awesome, I'll check out your changes!

**Comment by tholman** [comment]
Awesome stuff! I really enjoyed that back and forth, it all came out great!

**Pull request merged**
