### PR TITLE
Added dynamic contributors list

### PR DESCRIPTION
**Pull request by JohJakob**
I've added a dynamic contributors list based on JavaScript. It uses the GitHub API.

**Advantages**

- all contributors are listed
- contributors don't have to be added manually

**Disadvantages**

- GitHub's API is called (nearly) every time
- it is a bit slow
- links to Twitter accounts is replaced by links to GitHub accounts
- request limit of 60 requests per hour (per IP address) → solution: add OAuth authentication
- about 20 kB more page load

cc @tholman @vaidaslamanauskas @TJScalzo @Haroenv

### CODE REVIEW

**Comment by tholman** [comment]
Nice!

I'm a bit sketchy of the 60 requests per hour on that one... would it be possible to have something loop through posts, and see how many posts everyone has made.

Definitely want contributors to focus more on who's writing things, than who's adding code (really, github is more about who built the site... if that makes sense)

**Comment by JohJakob** [comment]
@tholman That would make sense. I'll try to build it.

**Comment by Haroenv** [comment]
In that case I think we could loop over the posts, get the author, and ignore doubles. That should give a list of people writing the posts and can be done without XHR

**Comment by JohJakob** [comment]
@Haroenv @tholman We can also count the posts of each author and create a ranking.

**Comment by Haroenv** [comment]
IMHO that's too competitive, but I don't make the decisions here ;)

**Comment by JohJakob** [comment]
@Haroenv I mean that authors with more posts are listed higher, but without a measurement. Just a normal list. But it's optional.

**Comment by Haroenv** [comment]
Oh if the count isn't visible that'd be good. Then you can get just the post contributors easily.

**Pull request closed without merging**
