### PR TITLE
added image and wrote a line

### PR DESCRIPTION
**Pull request by Haroenv**
I think this should be right now, @TJScalzo what do you think?

### CODE REVIEW

**Comment by JohJakob** [comment]
@Haroenv What are these conflicts?

**Comment by Haroenv** [comment]
Not sure, I'll make a different pull request to be sure

**Comment by TJScalzo** [comment]
It might because the branch you're pulling from is so far behind the main one? I'm not really sure.

**Comment by Haroenv** [comment]
see #132

**Pull request closed without merging**
