### PR TITLE
Add random page

### PR DESCRIPTION
**Pull request by TJScalzo**
I wanted to see if I could do this and I eventually figured it out.

I'm not sure if this should be added to the menu since it's getting a little crowded. I was thinking it could just exist as an easter egg for those who find it.

**BTW:**
I posted this as a PR because I want feedback and responses. I could've just added this directly to the site, but I want some discussion and ideas contributed before it's added.

### CODE REVIEW

**Comment by JohJakob** [comment]
@TJScalzo This is a cool idea! I would add it as an easter egg too.

**Comment by tholman** [comment]
Love it man! Merge it in 💃

**Comment by Haroenv** [comment]
What about 🔀 instead of the word?

**Comment by TJScalzo** [comment]
@JohJakob:
> What about 🔀 instead of the word?

I'm not sure I understand what you're saying. Do you mean put that emoji in the menu as a link to the page? Or name the actual page that emoji?
I was thinking it'd be an easter egg as in it's not actually linked to on the site. You'd have to look at Github or guess that it exists to find it.

**Comment by tholman** [comment]
Lol, merged it. I prefer `/random` to the emoji ;)

**Comment by Haroenv** [comment]
I mean the emoji/that icon as svg somewhere (not necessarily in the menu) and it'd link to `/random`.

**Comment by TJScalzo** [comment]
I drafted up what that could look like @Haroenv but I'm not at my computer anymore so I can't show a screenshot. I'll think of some places where a shuffle icon wouldn't be very obvious.

**Comment by tholman** [comment]
I think its great how it is, personally. Secret, but not too secret since ppl can see the code :)

**Pull request merged**
