### PR TITLE
Fixed some typos + tiny improvements

### PR DESCRIPTION
**Pull request by JohJakob**
Updated posts "Keep Portland Weird", "KatLeidoscope", "Sweaterify It",
"Eelslap", "Fornasetti Secret Page" and "NY Library Public Domain
Collections"

### CODE REVIEW

**Comment by tholman** [comment]
:pray:

**Comment by JohJakob** [comment]
I'm back :D

**Comment by vaidaslamanauskas** [comment]
C' mon, removing slashes :) Also, I think that "why does that exist?" should be lowercase because it is not a new sentence. But meh, who cares. All good :+1: :pray:

**Comment by JohJakob** [comment]
Every bit counts! :D
You're right, nobody cares, but actually "Why does that exist?" is a new sentence in quotes ;)

**Pull request merged**
