### PR TITLE
Minor grammar fix and link fixes

### PR DESCRIPTION
**Pull request by TJScalzo**
I added a missing apostrophe and removed some slashes at the end of links. Like I say in the commit message I'm not sure if it's required but I've seen other people remove them.

### CODE REVIEW

**Comment by vaidaslamanauskas** [comment]
It is super unnecessary, but well :smiley:

**Comment by TJScalzo** [comment]
@vaidaslamanauskas at least I threw in a real change as well right? :smile:

**Comment by vaidaslamanauskas** [comment]
I guess :smile:

**Comment by JohJakob** [comment]
@TJScalzo I'm the one removing slashes at the end of links :smile: and it is indeed super unnecessary.

**Comment by tholman** [comment]
Will always encourage!

...

Will also totally forget slashes in everything too!

**Pull request merged**
